// Genera migration/source/*.sql y migration/inventory.md a partir de los JSON del catálogo.
import fs from 'node:fs';
import path from 'node:path';

const S = path.dirname(new URL(import.meta.url).pathname);
const OUT = process.argv[2];
const SNAP = '2026-09-29';
const load = (n) => JSON.parse(fs.readFileSync(path.join(S, n + '.json'), 'utf8'));

const redact = (s) =>
  s == null ? s : String(s)
    .replace(/eyJ[\w-]{10,}\.[\w-]{10,}\.[\w-]{10,}/g, '<SUPABASE_ANON_KEY>')
    .replace(/sb_publishable_[\w-]+/g, '<SUPABASE_PUBLISHABLE_KEY>')
    .replace(/sb_secret_[\w-]+/g, '<SUPABASE_SECRET_KEY>');

const OWN = ['public', 'archive', 'private', 'timeclock'];
const functions = load('functions');
const columns = load('columns');
const constraints = load('constraints');
const indexes = load('indexes');
const relations = load('relations');
const views = load('views');
const misc = load('misc');
const cron = load('cron').map(({ _pad, ...j }) => j);

const q = (id) => (/^[a-z_][a-z0-9_]*$/.test(id) ? id : '"' + id.replace(/"/g, '""') + '"');
const fq = (s, n) => `${q(s)}.${q(n)}`;
const header = (title) =>
  `-- ${title}\n-- Origen: Supabase GES (wfzdrqfurwnakrfdnbgf), esquemas ${OWN.join(', ')}.\n` +
  `-- Extraído del catálogo el ${SNAP} (solo lectura). Referencia: NO ejecutar en Azure.\n` +
  `-- Credenciales redactadas como <SUPABASE_*>.\n\n`;

const src = path.join(OUT, 'source');
fs.mkdirSync(path.join(src, 'catalog'), { recursive: true });
const write = (f, s) => fs.writeFileSync(path.join(src, f), s);

// --- 01 enums
const enums = misc.filter((x) => x.kind === 'enum' && OWN.includes(x.schema));
write('01_enums.sql', header('Tipos enum') +
  enums.map((e) => `CREATE TYPE ${fq(e.schema, e.name)} AS ENUM (${e.def});`).join('\n') + '\n');

// --- 02 tablas
const byTable = (arr) => arr.reduce((m, x) => ((m[x.schema + '.' + x.tbl] ||= []).push(x), m), {});
const colsBy = byTable(columns);
const consBy = byTable(constraints);
const idxBy = byTable(indexes);
const tableKeys = Object.keys(colsBy).sort();
let t = header('Tablas (columnas + PK/UNIQUE/CHECK/FK)');
for (const k of tableKeys) {
  const [s, n] = k.split('.');
  const lines = colsBy[k].map((c) => {
    let l = `  ${q(c.col)} ${c.type}`;
    if (c.ident === 'a') l += ' GENERATED ALWAYS AS IDENTITY';
    else if (c.ident === 'd') l += ' GENERATED BY DEFAULT AS IDENTITY';
    else if (c.gen === 's') l += ` GENERATED ALWAYS AS (${c.def}) STORED`;
    else if (c.def != null) l += ` DEFAULT ${c.def}`;
    if (c.notnull) l += ' NOT NULL';
    return l;
  });
  for (const c of consBy[k] || []) if (c.type !== 'f') lines.push(`  CONSTRAINT ${q(c.name)} ${c.def}`);
  t += `CREATE TABLE ${fq(s, n)} (\n${lines.join(',\n')}\n);\n\n`;
}
t += '-- Foreign keys (al final para no depender del orden de creación)\n';
for (const k of tableKeys) for (const c of consBy[k] || []) if (c.type === 'f') {
  const [s, n] = k.split('.');
  t += `ALTER TABLE ${fq(s, n)} ADD CONSTRAINT ${q(c.name)} ${c.def};\n`;
}
write('02_tables.sql', redact(t));

// --- 03 índices (sin los que respaldan PK/UNIQUE)
write('03_indexes.sql', header('Índices (excluye los de PK/UNIQUE)') +
  indexes.map((i) => i.def + ';').join('\n') + '\n');

// --- 04/05 vistas y MVs
const vw = views.filter((v) => v.kind === 'v');
const mv = views.filter((v) => v.kind === 'm');
write('04_views.sql', redact(header('Vistas') +
  vw.map((v) => `CREATE OR REPLACE VIEW ${fq(v.schema, v.name)} AS\n${v.def.trim()}\n`).join('\n')));
write('05_materialized_views.sql', redact(header('Vistas materializadas') +
  mv.map((v) => `CREATE MATERIALIZED VIEW ${fq(v.schema, v.name)} AS\n${v.def.trim().replace(/;$/, '')}\nWITH NO DATA;\n`).join('\n')));

// --- 06 funciones
write('06_functions.sql', redact(header('Funciones y procedimientos (sin los de extensiones)') +
  functions.map((f) => f.ddl.trim().replace(/;?$/, ';')).join('\n\n') + '\n'));

// --- 07 triggers
const trg = misc.filter((x) => x.kind === 'trigger');
write('07_triggers.sql', header('Triggers') + trg.map((x) => x.def + ';').join('\n') + '\n');

// --- 08 políticas RLS
const pol = misc.filter((x) => x.kind === 'policy').map((x) => ({ ...x, p: JSON.parse(x.def) }));
const rlsOn = relations.filter((r) => r.rls && ['r', 'p'].includes(r.kind));
let p = header('Row Level Security: tablas con RLS activo y sus políticas');
p += rlsOn.map((r) => `ALTER TABLE ${fq(r.schema, r.tbl)} ENABLE ROW LEVEL SECURITY;`).join('\n') + '\n\n';
for (const x of pol) {
  const roles = Array.isArray(x.p.roles) ? x.p.roles : String(x.p.roles).replace(/[{}]/g, '').split(',');
  p += `CREATE POLICY ${q(x.name)} ON ${fq(x.schema, x.tbl)} AS ${x.p.permissive} FOR ${x.p.cmd} TO ${roles.join(', ')}` +
    (x.p.using ? `\n  USING (${x.p.using})` : '') + (x.p.check ? `\n  WITH CHECK (${x.p.check})` : '') + ';\n\n';
}
write('08_rls_policies.sql', redact(p));

// --- 09 cron
write('09_cron_jobs.sql', redact(header('Jobs de pg_cron (cron.job). Estadísticas de 7 días en el comentario') +
  cron.map((j) => `-- #${j.jobid} ${j.jobname} | ${j.schedule} | ${j.active ? 'activo' : 'INACTIVO'} | ` +
    `runs 7d: ${j.runs_7d}, fallos: ${j.failed_7d}, prom: ${j.avg_secs ?? '-'} s\n` +
    `SELECT cron.schedule('${j.jobname}', '${j.schedule}', $cron$${j.command.trim()}$cron$);\n`).join('\n')));

// --- catálogo JSON (para generar T-SQL por script en la Fase 1)
const cat = (f, d) => fs.writeFileSync(path.join(src, 'catalog', f), redact(JSON.stringify(d, null, 1)) + '\n');
cat('columns.json', columns); cat('constraints.json', constraints); cat('indexes.json', indexes);
cat('relations.json', relations); cat('cron_jobs.json', cron);

// ================= inventory.md =================
const MODULES = [
  ['Temporal / respaldo', /^(_|wh_whr_backfill_universo$|.*_backup|.*_bak$|.*_old$|tmp_)/],
  ['Market intelligence', /^mi_/],
  ['Integración Magaya', /^(magaya_|wr_|ar_ap_sync_queue$)/],
  ['Consolidados', /^consolidado/],
  ['Bodega Miami', /^(wh_|cl_|picking_|loading_|staging_|manifest_|bodega_)/],
  ['Comisiones', /^cmm_/],
  ['Finanzas', /^(finanzas_|cash_|bank_|scheduled_payment|vendor_|arap_|fx_|nomina_|caja_)/],
  ['Operaciones', /^(ops_|shipments?$|shipment_|liq_|cierres_liquidacion)/],
  ['Tarifas', /^(rates?$|rate_|air_rate|contracts?$|contract_|surcharge|freight_|shipco_|inland_|lcl_|drayage_|tariff_|agent_rate)/],
  ['CRM y ventas', /^(clients?$|client_|contacts?$|contact_|deals?$|deal_|sales_|quotes?$|quote_|prospect)/],
  ['Seguridad y usuarios', /^(users?$|user_|roles?$|role_|impersonation_|login_|audit_|permissions?)/],
  ['Christmas Palace', /^christmas_/],
  ['Otros', /^(visitors?|visits?|job_applicant|inhouse_|monday_|carrier_advisor)/],
];
const moduleOf = (s, n) => (s !== 'public' ? `Esquema ${s}` : (MODULES.find(([, re]) => re.test(n)) || ['Sin clasificar'])[0]);

const fkOut = {}, fkIn = {};
for (const c of constraints) if (c.type === 'f') {
  const k = c.schema + '.' + c.tbl;
  (fkOut[k] ||= new Set()).add(c.ref);
  (fkIn[c.ref] ||= new Set()).add(k);
}
const hasPk = new Set(constraints.filter((c) => c.type === 'p').map((c) => c.schema + '.' + c.tbl));
const fmtN = (n) => Number(n).toLocaleString('en-US');
const fmtB = (b) => (b >= 1 << 30 ? (b / (1 << 30)).toFixed(2) + ' GB' : b >= 1 << 20 ? (b / (1 << 20)).toFixed(1) + ' MB' : Math.round(b / 1024) + ' KB');

const tables = relations.filter((r) => ['r', 'p'].includes(r.kind)).map((r) => {
  const k = r.schema + '.' + r.tbl;
  const rows = Math.max(Number(r.live_rows), Number(r.est_rows));
  const mod = moduleOf(r.schema, r.tbl);
  const migra = mod === 'Temporal / respaldo' ? 'No (confirmar)' : rows === 0 ? 'Revisar (vacía)' : 'Sí';
  return { ...r, k, rows, mod, migra, pk: hasPk.has(k), out: [...(fkOut[k] || [])], in: [...(fkIn[k] || [])] };
});
const totalBytes = tables.reduce((a, t) => a + Number(t.bytes), 0);

const typeCount = {};
for (const c of columns) {
  const base = c.type.replace(/\(.*\)/, '').replace(/^.*\./, '');
  typeCount[base] = (typeCount[base] || 0) + 1;
}
const enumNames = new Set(enums.map((e) => e.name));

let md = `# Inventario de GES (Supabase → Azure SQL)\n\n`;
md += `> Generado el ${SNAP} desde el catálogo de \`wfzdrqfurwnakrfdnbgf\` (solo SELECT). ` +
  `Filas = máx(n_live_tup, reltuples): **aproximadas**, no son conteos exactos. ` +
  `El módulo se asigna por prefijo (CLAUDE.md §3.3) y **hay que validarlo**. ` +
  `La columna "¿Migra?" es una **propuesta**; la decisión es de Andrés.\n\n`;

md += `## Resumen\n\n| Objeto | Cantidad |\n|---|---|\n`;
const cnt = (s, kind) => relations.filter((r) => r.schema === s && kind.includes(r.kind)).length;
for (const s of OWN) md += `| Tablas \`${s}\` | ${cnt(s, ['r', 'p'])} |\n`;
md += `| Vistas (${OWN.map((s) => s + ': ' + vw.filter((v) => v.schema === s).length).join(', ')}) | ${vw.length} |\n| Vistas materializadas | ${mv.length} |\n`;
md += `| Funciones/procedimientos propios | ${functions.length} (más 7 que vienen de extensiones y no se exportan) |\n`;
md += `| Triggers | ${trg.length} |\n| Políticas RLS | ${pol.length} |\n| Enums propios | ${enums.length} |\n`;
md += `| Índices (sin PK/UNIQUE) | ${indexes.length} |\n| Cron jobs | ${cron.length} (${cron.filter((j) => j.active).length} activos) |\n`;
md += `| Tamaño total de las tablas (con índices y TOAST) | ${fmtB(totalBytes)} |\n\n`;
md += `**Diferencias con CLAUDE.md §3.1:** hay 330 funciones propias más 7 de extensiones, que suman las 337 del documento. ` +
  `Políticas: ${pol.length} (el documento dice 563; no verifiqué la causa de la diferencia). ` +
  `Hay ${enums.length} enums propios; el catálogo tiene 48 en total contando \`auth\`, \`storage\`, etc.\n\n`;

// por módulo
const mods = {};
for (const t of tables) { const m = (mods[t.mod] ||= { n: 0, rows: 0, bytes: 0, vac: 0 }); m.n++; m.rows += t.rows; m.bytes += Number(t.bytes); if (!t.rows) m.vac++; }
md += `## Por módulo\n\n| Módulo | Tablas | Vacías | Filas aprox. | Tamaño |\n|---|---|---|---|---|\n`;
for (const [m, v] of Object.entries(mods).sort((a, b) => b[1].bytes - a[1].bytes))
  md += `| ${m} | ${v.n} | ${v.vac} | ${fmtN(v.rows)} | ${fmtB(v.bytes)} |\n`;

// alertas
const noRls = tables.filter((t) => t.schema === 'public' && !t.rls);
const rlsNoPol = tables.filter((t) => t.rls && Number(t.policies) === 0);
const noPk = tables.filter((t) => !t.pk);
md += `\n## Alertas para la migración\n\n`;
md += `- **Tablas en \`public\` sin RLS** (${noRls.length}), expuestas a la anon key: ${noRls.map((t) => '`' + t.tbl + '`').join(', ') || 'ninguna'}.\n`;
md += `- **RLS activo pero sin políticas** (${rlsNoPol.length}); solo las ve service_role: ${rlsNoPol.map((t) => '`' + t.k + '`').join(', ') || 'ninguna'}.\n`;
md += `- **Tablas sin PK** (${noPk.length}). Hay que definir la clave antes de cargarlas a SQL Server: ${noPk.map((t) => '`' + t.k + '`').join(', ') || 'ninguna'}.\n`;
md += `- **Tablas vacías** (${tables.filter((t) => !t.rows).length}). Son candidatas a no migrarse (ver la columna "¿Migra?").\n`;
md += `- **La anon key está escrita en ${cron.filter((j) => /eyJ/.test(j.command)).length} cron jobs y en 1 función** (\`trg_credit_request_approved_notify\`). En Azure debe ir en Key Vault o en app settings.\n\n`;

// tipos
md += `## Tipos de columna usados (para mapear a T-SQL)\n\n| Tipo Postgres | Columnas | Destino sugerido (§5) |\n|---|---|---|\n`;
const MAP = { uuid: 'UNIQUEIDENTIFIER', text: 'NVARCHAR(MAX) / NVARCHAR(n)', 'character varying': 'NVARCHAR(n)', 'timestamp with time zone': 'DATETIMEOFFSET',
  'timestamp without time zone': 'DATETIME2', boolean: 'BIT', numeric: 'DECIMAL(p,s)', jsonb: 'NVARCHAR(MAX) + ISJSON', json: 'NVARCHAR(MAX) + ISJSON',
  integer: 'INT', bigint: 'BIGINT', smallint: 'SMALLINT', date: 'DATE', 'double precision': 'FLOAT', real: 'REAL',
  'text[]': 'tabla hija o JSON', 'uuid[]': 'tabla hija o JSON', 'time without time zone': 'TIME', bytea: 'VARBINARY(MAX)', interval: '(sin equivalente: segundos en INT/BIGINT)',
  tsvector: '(Full-Text Search)', inet: 'NVARCHAR(45)', 'character': 'NCHAR(n)', 'integer[]': 'tabla hija o JSON', 'numeric[]': 'tabla hija o JSON' };
for (const [ty, n] of Object.entries(typeCount).sort((a, b) => b[1] - a[1]))
  md += `| \`${ty}\` | ${n} | ${MAP[ty] || (enumNames.has(ty) ? 'CHECK o tabla catálogo (enum)' : '**revisar**')} |\n`;

// cron
md += `\n## Cron jobs (a reemplazar por Azure Functions Timer)\n\n| # | Nombre | Schedule | Activo | Tipo | Runs 7d | Fallos 7d |\n|---|---|---|---|---|---|---|\n`;
for (const j of cron) {
  const tipo = /net\.http_post/.test(j.command) ? 'HTTP → edge fn `' + ((j.command.match(/functions\/v1\/([\w-]+)/) || [])[1] || '?') + '`' : 'SQL';
  md += `| ${j.jobid} | \`${j.jobname}\` | \`${j.schedule}\` | ${j.active ? 'sí' : 'no'} | ${tipo} | ${j.runs_7d} | ${j.failed_7d} |\n`;
}

// vistas materializadas
md += `\n## Vistas materializadas (${mv.length})\n\nEn SQL Server no existen. Opciones: indexed view (con restricciones) o una tabla de resumen que refresque un job.\n\n`;
md += mv.map((v) => `\`${v.schema}.${v.name}\``).join(', ') + '\n';

// detalle tablas
md += `\n## Detalle por tabla\n\nFK→ = tablas a las que apunta. ←FK = número de tablas que la referencian.\n`;
for (const [m] of Object.entries(mods).sort((a, b) => b[1].bytes - a[1].bytes)) {
  md += `\n### ${m}\n\n| Tabla | Filas aprox. | Tamaño | PK | RLS / pol. | Trg | FK→ | ←FK | ¿Migra? |\n|---|---|---|---|---|---|---|---|---|\n`;
  for (const t of tables.filter((x) => x.mod === m).sort((a, b) => b.bytes - a.bytes)) {
    const name = t.schema === 'public' ? t.tbl : t.k;
    const out = t.out.map((r) => r.replace(/^public\./, '')).join(', ');
    md += `| \`${name}\` | ${fmtN(t.rows)} | ${fmtB(Number(t.bytes))} | ${t.pk ? 'sí' : '**no**'} | ${t.rls ? 'sí' : '**no**'} / ${t.policies} | ${t.triggers} | ${out} | ${t.in.length} | ${t.migra} |\n`;
  }
}
fs.writeFileSync(path.join(OUT, 'inventory.md'), redact(md));
console.log('ok', tables.length, 'tablas');
