-- Triggers
-- Origen: Supabase GES (wfzdrqfurwnakrfdnbgf), esquemas public, archive, private, timeclock.
-- Extraído del catálogo el 2026-09-29 (solo lectura). Referencia: NO ejecutar en Azure.
-- Credenciales redactadas como <SUPABASE_*>.

CREATE TRIGGER legacy_agent_rates_solo_lectura BEFORE INSERT OR UPDATE ON public._legacy_agent_rates FOR EACH ROW EXECUTE FUNCTION tg_legacy_agent_rates_solo_lectura();
CREATE TRIGGER trigger_update_activity_metrics AFTER INSERT ON public.activity_logs FOR EACH ROW EXECUTE FUNCTION update_activity_metrics();
CREATE TRIGGER agent_office_updated_at_trg BEFORE UPDATE ON public.agent_office_mapping FOR EACH ROW EXECUTE FUNCTION tg_set_updated_at();
CREATE TRIGGER update_agents_updated_at BEFORE UPDATE ON public.agents FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER christmas_bookings_audit AFTER INSERT OR DELETE OR UPDATE ON public.christmas_bookings FOR EACH ROW EXECUTE FUNCTION christmas_audit();
CREATE TRIGGER christmas_bookings_set_nra BEFORE INSERT ON public.christmas_bookings FOR EACH ROW EXECUTE FUNCTION christmas_bookings_set_nra();
CREATE TRIGGER christmas_destinations_audit AFTER INSERT OR DELETE OR UPDATE ON public.christmas_destinations FOR EACH ROW EXECUTE FUNCTION christmas_audit();
CREATE TRIGGER christmas_fee_overrides_audit AFTER INSERT OR DELETE OR UPDATE ON public.christmas_fee_overrides FOR EACH ROW EXECUTE FUNCTION christmas_audit();
CREATE TRIGGER christmas_global_settings_audit AFTER INSERT OR DELETE OR UPDATE ON public.christmas_global_settings FOR EACH ROW EXECUTE FUNCTION christmas_audit();
CREATE TRIGGER christmas_pallet_presets_audit AFTER INSERT OR DELETE OR UPDATE ON public.christmas_pallet_presets FOR EACH ROW EXECUTE FUNCTION christmas_audit();
CREATE TRIGGER christmas_products_audit AFTER INSERT OR DELETE OR UPDATE ON public.christmas_products FOR EACH ROW EXECUTE FUNCTION christmas_audit();
CREATE TRIGGER christmas_tenants_audit AFTER INSERT OR DELETE OR UPDATE ON public.christmas_tenants FOR EACH ROW EXECUTE FUNCTION christmas_audit();
CREATE TRIGGER christmas_user_profiles_audit AFTER INSERT OR DELETE OR UPDATE ON public.christmas_user_profiles FOR EACH ROW EXECUTE FUNCTION christmas_audit();
CREATE TRIGGER christmas_user_profiles_set_updated_at BEFORE UPDATE ON public.christmas_user_profiles FOR EACH ROW EXECUTE FUNCTION christmas_set_updated_at();
CREATE TRIGGER trg_client_visit_to_activity AFTER INSERT OR UPDATE OF status ON public.client_visits FOR EACH ROW EXECUTE FUNCTION client_visit_to_activity();
CREATE TRIGGER trg_client_visits_touch BEFORE UPDATE ON public.client_visits FOR EACH ROW EXECUTE FUNCTION touch_client_visits_updated_at();
CREATE TRIGGER tg_clients_backfill_intel_matches AFTER INSERT OR UPDATE OF ruc ON public.clients FOR EACH ROW WHEN ((new.ruc IS NOT NULL)) EXECUTE FUNCTION tg_clients_backfill_intel_matches();
CREATE TRIGGER tg_clients_track_soft_delete BEFORE UPDATE OF deleted_at ON public.clients FOR EACH ROW EXECUTE FUNCTION tg_clients_track_soft_delete();
CREATE TRIGGER tg_protect_credit_fields BEFORE UPDATE ON public.clients FOR EACH ROW EXECUTE FUNCTION tg_protect_credit_fields();
CREATE TRIGGER trg_consolidado_avisos_touch BEFORE UPDATE ON public.consolidado_avisos FOR EACH ROW EXECUTE FUNCTION consolidado_avisos_touch();
CREATE TRIGGER trg_consolidado_pieza_no_duplicada BEFORE INSERT OR UPDATE ON public.consolidado_linea_piezas FOR EACH ROW EXECUTE FUNCTION consolidado_pieza_no_duplicada();
CREATE TRIGGER trg_consolidado_no_tenant_impo BEFORE INSERT OR UPDATE ON public.consolidado_lineas FOR EACH ROW EXECUTE FUNCTION consolidado_linea_no_tenant_impo();
CREATE TRIGGER trg_consolidado_servicio BEFORE INSERT ON public.consolidados FOR EACH ROW EXECUTE FUNCTION consolidado_hereda_servicio();
CREATE TRIGGER coordination_tasks_updated_at_trg BEFORE UPDATE ON public.coordination_tasks FOR EACH ROW EXECUTE FUNCTION coordination_tasks_set_updated_at();
CREATE TRIGGER credit_requests_approved_notify AFTER UPDATE ON public.credit_requests FOR EACH ROW EXECUTE FUNCTION trg_credit_request_approved_notify();
CREATE TRIGGER credit_requests_recompute AFTER INSERT OR DELETE OR UPDATE ON public.credit_requests FOR EACH ROW EXECUTE FUNCTION trg_credit_requests_recompute();
CREATE TRIGGER on_credit_request_decision AFTER UPDATE ON public.credit_requests FOR EACH ROW EXECUTE FUNCTION notify_credit_decision_update();
CREATE TRIGGER on_credit_request_insert AFTER INSERT ON public.credit_requests FOR EACH ROW EXECUTE FUNCTION notify_credit_request_insert();
CREATE TRIGGER update_deals_updated_at BEFORE UPDATE ON public.deals FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_deals_updated_at_trigger BEFORE UPDATE ON public.deals FOR EACH ROW EXECUTE FUNCTION update_deals_updated_at();
CREATE TRIGGER update_dispatches_updated_at BEFORE UPDATE ON public.dispatches FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_ec_fcl_local_charges_audit BEFORE INSERT OR UPDATE ON public.ec_fcl_local_charges FOR EACH ROW EXECUTE FUNCTION ec_fcl_local_charges_audit();
CREATE TRIGGER update_email_templates_updated_at BEFORE UPDATE ON public.email_templates FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_external_containers_updated_at BEFORE UPDATE ON public.external_containers FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_fcl_semanal_touch BEFORE UPDATE ON public.fcl_semanal FOR EACH ROW EXECUTE FUNCTION ops_vacios_touch();
CREATE TRIGGER trg_job_applicants_updated BEFORE UPDATE ON public.job_applicants FOR EACH ROW EXECUTE FUNCTION visitor_touch_updated_at();
CREATE TRIGGER trg_liq_lines_recalc AFTER INSERT OR DELETE OR UPDATE ON public.liq_settlement_lines FOR EACH ROW EXECUTE FUNCTION liq_lines_recalc_trigger();
CREATE TRIGGER trg_loading_materials_touch BEFORE UPDATE ON public.loading_materials FOR EACH ROW EXECUTE FUNCTION cl_touch_updated_at();
CREATE TRIGGER trg_touch_loading_tasks BEFORE UPDATE ON public.loading_tasks FOR EACH ROW EXECUTE FUNCTION cl_touch_updated_at();
CREATE TRIGGER trg_magaya_accounts_updated BEFORE UPDATE ON public.magaya_accounts FOR EACH ROW EXECUTE FUNCTION update_magaya_updated_at();
CREATE TRIGGER trg_magaya_charges_updated BEFORE UPDATE ON public.magaya_charge_definitions FOR EACH ROW EXECUTE FUNCTION update_magaya_updated_at();
CREATE TRIGGER trg_magaya_companies_updated BEFORE UPDATE ON public.magaya_companies FOR EACH ROW EXECUTE FUNCTION update_magaya_updated_at();
CREATE TRIGGER trg_sync_cr_items AFTER INSERT ON public.magaya_cr_items FOR EACH ROW EXECUTE FUNCTION sync_cr_items_to_wh_report();
CREATE TRIGGER trg_magaya_currencies_updated BEFORE UPDATE ON public.magaya_currencies FOR EACH ROW EXECUTE FUNCTION update_magaya_updated_at();
CREATE TRIGGER trg_magaya_entities_updated BEFORE UPDATE ON public.magaya_entities FOR EACH ROW EXECUTE FUNCTION update_magaya_updated_at();
CREATE TRIGGER magaya_payment_extract_trigger AFTER INSERT OR UPDATE OF raw_xml ON public.magaya_transactions FOR EACH ROW EXECUTE FUNCTION extract_magaya_payment_items();
CREATE TRIGGER trg_magaya_transactions_updated BEFORE UPDATE ON public.magaya_transactions FOR EACH ROW EXECUTE FUNCTION update_magaya_updated_at();
CREATE TRIGGER mwr_redactar_notas BEFORE INSERT OR UPDATE OF notes ON public.magaya_warehouse_receipts FOR EACH ROW EXECUTE FUNCTION wr_redactar_notas();
CREATE TRIGGER trg_magaya_wr_force_company BEFORE INSERT OR UPDATE ON public.magaya_warehouse_receipts FOR EACH ROW EXECUTE FUNCTION magaya_wr_force_company();
CREATE TRIGGER wr_auto_match_trg AFTER INSERT ON public.magaya_warehouse_receipts FOR EACH ROW EXECUTE FUNCTION tg_match_wr_on_insert();
CREATE TRIGGER wr_auto_match_update_trg AFTER UPDATE OF status ON public.magaya_warehouse_receipts FOR EACH ROW EXECUTE FUNCTION tg_match_wr_on_update();
CREATE TRIGGER mwri_redactar_notas BEFORE INSERT OR UPDATE OF notes ON public.magaya_wr_items FOR EACH ROW EXECUTE FUNCTION wr_redactar_notas();
CREATE TRIGGER trg_fix_wr_item_location BEFORE INSERT OR UPDATE ON public.magaya_wr_items FOR EACH ROW EXECUTE FUNCTION app_fix_wr_item_location();
CREATE TRIGGER trg_magaya_wr_items_guarda BEFORE INSERT OR DELETE OR UPDATE ON public.magaya_wr_items FOR EACH ROW EXECUTE FUNCTION magaya_wr_items_guarda();
CREATE TRIGGER trg_sync_wr_items AFTER INSERT ON public.magaya_wr_items FOR EACH ROW EXECUTE FUNCTION sync_wr_items_to_wh_report();
CREATE TRIGGER trg_touch_manifest_items BEFORE UPDATE ON public.manifest_items FOR EACH ROW EXECUTE FUNCTION cl_touch_updated_at();
CREATE TRIGGER trg_touch_manifest_sources BEFORE UPDATE ON public.manifest_sources FOR EACH ROW EXECUTE FUNCTION cl_touch_updated_at();
CREATE TRIGGER mi_canonical_actor_updated_at_trg BEFORE UPDATE ON public.mi_canonical_actor FOR EACH ROW EXECUTE FUNCTION tg_set_updated_at();
CREATE TRIGGER mi_match_review_updated_at_trg BEFORE UPDATE ON public.mi_match_review_queue FOR EACH ROW EXECUTE FUNCTION tg_set_updated_at();
CREATE TRIGGER mi_intel_classify_trg BEFORE INSERT OR UPDATE OF carrier_raw, forwarder_raw_receptor, forwarder_raw_liberador, partner_raw, forwarder_canonical_id, partner_canonical_id, is_direct_no_forwarder ON public.mi_shipment_intel FOR EACH ROW EXECUTE FUNCTION mi_intel_classify_trg_fn();
CREATE TRIGGER mi_shipment_intel_updated_at_trg BEFORE UPDATE ON public.mi_shipment_intel FOR EACH ROW EXECUTE FUNCTION tg_set_updated_at();
CREATE TRIGGER tg_mi_intel_match_ruc BEFORE INSERT ON public.mi_shipment_intel FOR EACH ROW EXECUTE FUNCTION tg_mi_intel_match_ruc();
CREATE TRIGGER trg_ops_vacios_touch BEFORE UPDATE ON public.ops_devolucion_vacios FOR EACH ROW EXECUTE FUNCTION ops_vacios_touch();
CREATE TRIGGER trg_ops_transfers_guard BEFORE UPDATE ON public.ops_transfers FOR EACH ROW EXECUTE FUNCTION tg_ops_transfers_guard();
CREATE TRIGGER pba_payments_updated_at_trg BEFORE UPDATE ON public.pba_payments FOR EACH ROW EXECUTE FUNCTION tg_set_updated_at();
CREATE TRIGGER trg_forklift_cert BEFORE INSERT OR UPDATE OF assigned_to, task_type ON public.picking_tasks FOR EACH ROW EXECUTE FUNCTION enforce_forklift_cert();
CREATE TRIGGER trg_on_picking_task_closed AFTER UPDATE OF status ON public.picking_tasks FOR EACH ROW EXECUTE FUNCTION on_picking_task_closed();
CREATE TRIGGER trg_picking_task_split_limit BEFORE INSERT ON public.picking_tasks FOR EACH ROW EXECUTE FUNCTION enforce_picking_task_split_limit();
CREATE TRIGGER trg_touch_picking_tasks BEFORE UPDATE ON public.picking_tasks FOR EACH ROW EXECUTE FUNCTION cl_touch_updated_at();
CREATE TRIGGER trg_pricing_rules_updated_at BEFORE UPDATE ON public.pricing_rules FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER prospect_enrichment_ec_updated_at BEFORE UPDATE ON public.prospect_enrichment_ec FOR EACH ROW EXECUTE FUNCTION prospect_enrichment_ec_touch_updated_at();
CREATE TRIGGER quotes_protege_created_by_trg BEFORE UPDATE ON public.quotes FOR EACH ROW EXECUTE FUNCTION quotes_protege_created_by();
CREATE TRIGGER trg_reception_hosts_updated BEFORE UPDATE ON public.reception_hosts FOR EACH ROW EXECUTE FUNCTION visitor_touch_updated_at();
CREATE TRIGGER trg_bloqueo_ops BEFORE INSERT OR DELETE OR UPDATE ON public.shipment_agents FOR EACH ROW EXECUTE FUNCTION tg_shipment_hijos_bloqueo_ops();
CREATE TRIGGER trg_bloqueo_ops BEFORE INSERT OR DELETE OR UPDATE ON public.shipment_containers FOR EACH ROW EXECUTE FUNCTION tg_shipment_hijos_bloqueo_ops();
CREATE TRIGGER trg_ops_vacios_seed AFTER INSERT ON public.shipment_containers FOR EACH ROW EXECUTE FUNCTION ops_vacios_desde_contenedor();
CREATE TRIGGER trg_ops_vacios_seed_upd AFTER UPDATE OF container_number ON public.shipment_containers FOR EACH ROW WHEN (((COALESCE(TRIM(BOTH FROM new.container_number), ''::text) <> ''::text) AND (new.container_number IS DISTINCT FROM old.container_number))) EXECUTE FUNCTION ops_vacios_desde_contenedor();
CREATE TRIGGER trg_ops_vacios_sync_num AFTER UPDATE OF container_number, size_type ON public.shipment_containers FOR EACH ROW EXECUTE FUNCTION ops_vacios_sync_numero();
CREATE TRIGGER trg_bloqueo_ops BEFORE INSERT OR DELETE OR UPDATE ON public.shipment_shippers FOR EACH ROW EXECUTE FUNCTION tg_shipment_hijos_bloqueo_ops();
CREATE TRIGGER pba_sync_desde_shipment_trg AFTER INSERT OR UPDATE OF pba_amount, pba_currency, client_id, hbl, mbl ON public.shipments FOR EACH ROW EXECUTE FUNCTION pba_sync_desde_shipment();
CREATE TRIGGER shipments_set_defaults_trg BEFORE INSERT ON public.shipments FOR EACH ROW EXECUTE FUNCTION shipments_set_defaults();
CREATE TRIGGER shipments_updated_at_trg BEFORE UPDATE ON public.shipments FOR EACH ROW EXECUTE FUNCTION tg_set_updated_at();
CREATE TRIGGER trg_protect_pba BEFORE INSERT OR UPDATE ON public.shipments FOR EACH ROW EXECUTE FUNCTION app_protect_pba_fields();
CREATE TRIGGER trg_shipments_bloqueo_ops BEFORE UPDATE ON public.shipments FOR EACH ROW EXECUTE FUNCTION tg_shipments_bloqueo_ops();
CREATE TRIGGER si_touch BEFORE UPDATE ON public.shipping_instructions FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER trg_on_staging_check_closed AFTER UPDATE OF status ON public.staging_check_tasks FOR EACH ROW EXECUTE FUNCTION on_staging_check_closed();
CREATE TRIGGER trg_on_staging_check_created AFTER INSERT ON public.staging_check_tasks FOR EACH ROW EXECUTE FUNCTION on_staging_check_created();
CREATE TRIGGER trg_stager_not_picker BEFORE INSERT OR UPDATE OF assigned_to ON public.staging_check_tasks FOR EACH ROW EXECUTE FUNCTION enforce_stager_not_picker();
CREATE TRIGGER trg_touch_staging_check_tasks BEFORE UPDATE ON public.staging_check_tasks FOR EACH ROW EXECUTE FUNCTION cl_touch_updated_at();
CREATE TRIGGER trg_tariff_sheets_updated_at BEFORE UPDATE ON public.tariff_sheets FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trigger_calculate_total_hours BEFORE UPDATE ON public.time_entries FOR EACH ROW EXECUTE FUNCTION calculate_total_hours();
CREATE TRIGGER update_time_entries_updated_at BEFORE UPDATE ON public.time_entries FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER users_sync_role_trg BEFORE INSERT OR UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION tg_users_sync_role();
CREATE TRIGGER trg_visitor_badges_updated BEFORE UPDATE ON public.visitor_badges FOR EACH ROW EXECUTE FUNCTION visitor_touch_updated_at();
CREATE TRIGGER trg_visitors_updated BEFORE UPDATE ON public.visitors FOR EACH ROW EXECUTE FUNCTION visitor_touch_updated_at();
CREATE TRIGGER trg_visits_updated BEFORE UPDATE ON public.visits FOR EACH ROW EXECUTE FUNCTION visitor_touch_updated_at();
CREATE TRIGGER update_warehouse_containers_updated_at BEFORE UPDATE ON public.warehouse_containers FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_warehouse_tasks_updated_at BEFORE UPDATE ON public.warehouse_tasks FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_touch_warehouse_users BEFORE UPDATE ON public.warehouse_users FOR EACH ROW EXECUTE FUNCTION cl_touch_updated_at();
CREATE TRIGGER wh_notices_docs_internos BEFORE INSERT OR UPDATE OF attachments ON public.wh_notices FOR EACH ROW EXECUTE FUNCTION wh_notices_marcar_docs_internos();
CREATE TRIGGER wr_match_updated_at_trg BEFORE UPDATE ON public.wr_match_results FOR EACH ROW EXECUTE FUNCTION tg_set_updated_at();
